name: "Workflow3"

on:
  workflow_run:
    workflows: ["workflow1"]
    types:
      - completed

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: "Cat index.ts"
          run: cat "src/index.ts"