name: Unit Test

on: [push]

jobs:
  unitTest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: tsc

      - name: Run Test
        run: node dist/test1.js

  integrationTest:
    name: Integration Test
    needs: [Unit Test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: tsc

      - name: Run Test
        run: node dist/IntegrationTest.js