name: Integration Test

on:
  workflow_run:
    workflows: [Unit Test]
    types: [completed]

jobs:
  unitTest:
    needs: [Unit Test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install node js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: tsc

      - name: Run Test
        run: node dist/IntegrationTest.js